name: nota
description: "Minimalist note-taking app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  monitoring:
    path: packages/monitoring

  component_library:
    path: packages/component_library

  app_settings:
    path: packages/app_settings

  preferences_storage:
    path: packages/preferences_storage

  shared:
    path: packages/shared

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
