name: app_settings
description: "App settings (theme, color, locale) for qnotes."
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  preferences_storage:
    path: ../../preferences_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences_platform_interface: ^2.4.1
