name: preferences_bottom_sheet
description: "Preferences bottom sheet: theme, locale and note view mode."
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  preferences_repository:
    path: ../../preferences_repository
  shared:
    path: ../../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
