name: preferences_bottom_sheet
description: "Preferences bottom sheet: theme, locale and note view mode."
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  preferences_repository:
    path: ../../preferences_repository
  shared:
    path: ../../shared
  component_library:
    path: ../../component_library

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  shared_preferences_platform_interface: ^2.4.1

flutter:
  generate: true
