name: note_list
description: "Note list feature: displays, searches and manages the list of notes."
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.11.1
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.1
  shared:
    path: ../../shared
  notes_repository:
    path: ../../notes_repository
  preferences_repository:
    path: ../../preferences_repository
  component_library:
    path: ../../component_library

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  generate: true
